### ISSUE TITLE
Use TelegramV2rayCollector instead of ConfigCollector

### ISSUE THREAD

**Issue by yebekhe** [Mahdi0024/ProxyCollector#1]
Hi Dear Mahdi

I'm glad to see one of my projects is such useful for you but i wanna recommend you to use github.com/yebekhe/TelegramV2rayCollector instead of ConfigCollector Project.

Best Regards - YeBeKhe

**Comment by Mahdi0024** [comment]
Hi YeBeKhe,

Thanks for your suggestion and your extremely useful projects. I know your TelegramV2rayCollector project, and it’s a great tool, but I use both of your projects in ProxyCollector, as you can see from the readme file. Any duplicate proxies are removed anyway, so I don't think there could be a problem with that.
however, I'm keeping this issue open if you got anything else to say.
