### ISSUE TITLE
another providers

### ISSUE THREAD

**Issue by Graveyard9988** [Mahdi0024/ProxyCollector#5]
https://github.com/barry-far/V2ray-Configs
https://raw.githubusercontent.com/Barabama/FreeNodes/master/nodes/merged.txt
https://github.com/Kwinshadow/TelegramV2rayCollector/tree/main
https://github.com/Flik6/getNode
https://raw.githubusercontent.com/sashalsk/V2Ray/main/V2Ray-list-current
https://github.com/soroushmirzaei/telegram-configs-collector

**Comment by Mahdi0024** [comment]
Thank you for your suggestion. I've added these sources to the project.

**Comment by Graveyard9988** [comment]
https://github.com/ImMyron/V2ray
Hasn't been updated
